import { Menu, shell, app, Tray, BrowserWindow } from 'electron'

// This allows TypeScript to pick up the magic constant that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: never;


export  function create():BrowserWindow{
    let AppMainWindow : BrowserWindow
  
    AppMainWindow = new BrowserWindow({
      width: 1080,
      height: 1200,
      icon: 'resources/images/ExaltedOrb.png',
      title: 'POE Interface',
      show: true,
      webPreferences: {
        nodeIntegration: false,
        contextIsolation: true,
        //worldSafeExecuteJavaScript: true,
        preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
      }
    });
  
    // and load the index.html of the app.
    AppMainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
  
    // Open the DevTools.
    AppMainWindow.webContents.openDevTools();
  
    AppMainWindow.on('closed', () => {
      AppMainWindow = null
    })
  
    return AppMainWindow
}