
export interface poe_interfaceAPI {
  cleanup: (channel: string) => void
  send: (channel: string, ...arg: any[]) => Promise<any>
  sendSync: (channel: string, ...arg: any[]) => Promise<any>
  receive: (channel: string, func: (event: any, ...arg: any[]) => void) => void
  openExternal: (url: string) => void
  openWiki: (page: string) => void
}

declare global {
  interface Window {
    poe_interfaceAPI: poe_interfaceAPI
  }

  type IAppPlayer = {
    name: string
    level: number
    characterClass: string
    characterAscendancy?: string
    currentZoneName: string
    currentZoneAct: number
  }

  /****************************/
  export interface IActsGuide {
    identity: ActGuideIdentity
    acts: IActsGuideAct[]
  }

  export interface IActsGuideAct {
    act?: string
    actid: number
    zones: IActsGuideZone[]
  }

  export interface IActsGuideZone {
    hastrial?: boolean
    image?: string[]
    note: string
    level?: number
    name: string
    haspassive?: boolean
    questRewardsSkills?: boolean
    altimage?: string
    quest?: string
    hasRecipe?: boolean
    hasWaypoint?: boolean
    recipe?: Recipe
  }

  /****************************/
  export interface IClassesAscendancies {
    classe?: string
    ascendancy?: string[]
  }

  /***************************/
  export interface GuidesIdentity {
    name: string
    lang: string
    game_version: number
    filename?: string
    webAssetPath?: string
    sysAssetPath?: string
    readonly?: boolean
    class?: string
    url?: string
  }
  // eslint-disable-next-line @typescript-eslint/no-empty-interface
  export interface ActGuideIdentity extends GuidesIdentity {}

  export interface ClassGuideIdentity extends GuidesIdentity {
    // class: stringGuideIdentity
    class: string
  }

  /***************************/
  export interface IClassesGuide {
    identity: ClassGuideIdentity
    acts: IClassesGuideAct[]
  }

  export interface IClassesGuideAct {
    act: number
    notes?: string
    gears: IClassesGuideGear[]
    treeimage?: string
  }

  export interface IClassesGuideGear {
    id: number
    name: string
    notes?: string
    gem_info: IClassesGuideGemInfo[]
    gems?: IGems[]
    chasses?: string[]
  }

  export interface IClassesGuideGemInfo {
    name: string
    note?: string
  }

  /***************************/
  // Generated by https://quicktype.io
  export interface IGems {
    reward: IReward
    required_lvl: number
    color: string
    isReward: boolean
    isSupport: boolean
    buy: IBuy[]
    name: string
    isVaal: boolean
    gemTags: string[]
    iconPath: string
    isActive: boolean
    alt_name?: string[]
    note?: string
  }

  export interface IBuy {
    npc: string
    act: number
    town: string
    available_to: string[]
    quest_name: string
  }

  export interface IReward {
    rien?: number
  }

  /***************************/
  export interface IRichText {
    data: string[]
    classe: string
  }

  /***************************/
  export interface IActsZonesSkel {
    identity: GuidesIdentity;
    acts: IActsZonesSkelAct[];
  }

  export interface IActsZonesSkelAct {
    act: string;
    actid: number;
    zones: IActsZonesSkelZone[];
  }

  export interface IActsZonesSkelZone {
    hasRecipe?: boolean;
    haspassive?: boolean;
    hastrial?: boolean;
    level: number;
    name: string;
    quest?: string;
    questRewardsSkills: boolean;
    image?: string[];
    recipe?: Recipe;
    hasWaypoint?: boolean;
  }

  export interface Recipe {
    mods?: string[];
    tooltip?: string;
  }

}