# This is a basic workflow to help you get started with Actions

name: release tag

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  tagged-release:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    name: release for ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macOS-latest]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install deps
        run: yarn        
      - name: package 
        run: yarn package
      - name: make 
        run: yarn make
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          title: "Latest Build"
          files: |
            out/**/*.zip
            out/**/*.exe
            out/**/*.deb
            out/**/*.dmg
        
        
        
