# This is a basic workflow to help you get started with Actions

name: release tag

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  ubuntu-tagged-release:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    name: package for ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install deps
        run: yarn        
      - name: package 
        run: yarn package --platform linux --arch x64
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            out/**/*.zip
            out/**/*.deb

  windows-tagged-release:
    runs-on: windows-latest
    name: package for Windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install deps
        run: yarn        
      - name: package 
        run: yarn package
      - name: make 
        run: yarn make
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            out/**/*.zip
            out/**/*.exe
            
  darwin-tagged-release:
    runs-on: darwin-latest
    name: package for darwin-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: install deps
        run: yarn        
      - name: package 
        run: yarn package
      - name: make 
        run: yarn make
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            out/**/*.zip
            out/**/*.dmg
