# This is a basic workflow to help you get started with Actions

name: release tag

# Controls when the workflow will run
on:
  push:
    tags:
      - 'v*'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest
          
    runs-on: ${{ matrix.os }}
    name: build for ${{ matrix.os }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        
      - name: install deps
        run: yarn     
        
      - name: make $ {{ matrix.os }}
        run: yarn make 

      - name: Upload macOS release build
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'macos-latest' }}
        with:
          name: dist-darwin-files
          path: out/make/**/*        

      - name: Upload windows release build
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'windows-latest' }}
        with:
          name: dist-windows-files
          path: out/make/**/*        

      - name: Upload linux ubuntu release build
        uses: actions/upload-artifact@v2
        if: ${{ matrix.os == 'ubuntu-latest' }}
        with:
          name: dist-ubuntu-files
          path: out/make/**/*        

        
  prerelease:
    needs: build
    runs-on: ubuntu-latest
      
    steps:
      - name: Download binaries
        uses: actions/download-artifact@v2
        
      - name: Deploy ${{ tag }} release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
          files: |
            dist*/**/*

